### ISSUE TITLE
Links redirecting to Kuma instead of proper links

### ISSUE THREAD

**Issue by fersirni** [kumawallet/extension#19]
</code></pre>

## Current behavior

Links in both Bug Report and About Us sections are redirecting to the wallet tab.

## Expected behavior

All links should be redirecting accordingly.

## Minimal reproduction of the problem with instructions

1. Open de wallet
2. Go to the Gear button (down to the right)
3. Go to Bug Report or About Us
4. Click on any link

## Environment

<pre><code>
Kuma version: 0.2.5
</code></pre>

**Comment by 0xslipk** [comment]
This was an issue with the building of the extension. We fixed on [v0.2.6](https://github.com/kumawallet/extension/releases/tag/v0.2.6)
